### ISSUE TITLE
Android app can not display app and driver stores

### ISSUE THREAD

**Issue by bafu** [me-box/databox-app#6]
Clicked "App Store" or "Driver Store" in the sidebar, and got a blank content area.

---
Steps to Reproduce

1. In the login screen, enter the IP address of host, e.g. 192.168.1.7

    * I got the error logs from host's container session:

        ```
        container-manager	: �2018-12-27T16:31:09.291604318Z [ERROR]2018/12/27 16:31:09 http2: server: error reading preface from client 192.168.1.13:container-manager	: 36753: read tcp 172.18.0.4:443->192.168.1.13:36753: read: connection reset by peer
        container-manager	: �2018-12-27T16:31:10.283951257Z [ERROR]2018/12/27 16:31:10 /go/src/github.com/gorilla/mux/mux.go L162:Password validationcontainer-manager	:  error!
        ```

1. Enter the default password `VzAwb0rl+/xgR+bZwi5Rap9MMoVpiFEE`
1. Open the sidebar, and click "App Store" or "Driver Store"

---
Environment

* Docker: 18.06.1-ce
* Databox: v0.5.0
* Databox App: commit `f1a8f8f`

**Comment by mor1** [comment]
@bafu Thanks!

@Toshbrown @ktg Any progress on this one?

**Comment by ktg** [comment]
New working version of the app released and available in the Google Play Store. Trying to upload it to the Apple App Store now.
